/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author garci
 */
public class FrameMetodoCesar extends javax.swing.JFrame {

    /**
     * Creates new form FrameMetodoCesar
     */
    public FrameMetodoCesar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1Encriptar = new javax.swing.JButton();
        jButton2Limpiar = new javax.swing.JButton();
        jButton3Desencriptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1TextoPlano = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2TextoCifrado = new javax.swing.JTextArea();
        jTextFieldDesplazamiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo Cesar");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Metodo Cesar");

        jLabel2.setText("Texto Plano");

        jLabel3.setText("Texto Cifrado");

        jButton1Encriptar.setText("Encriptar");
        jButton1Encriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EncriptarActionPerformed(evt);
            }
        });

        jButton2Limpiar.setText("Limpiar");
        jButton2Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LimpiarActionPerformed(evt);
            }
        });

        jButton3Desencriptar.setText("Desencriptar");
        jButton3Desencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DesencriptarActionPerformed(evt);
            }
        });

        jTextArea1TextoPlano.setColumns(20);
        jTextArea1TextoPlano.setRows(5);
        jScrollPane1.setViewportView(jTextArea1TextoPlano);

        jTextArea2TextoCifrado.setColumns(20);
        jTextArea2TextoCifrado.setRows(5);
        jScrollPane2.setViewportView(jTextArea2TextoCifrado);

        jTextFieldDesplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDesplazamientoActionPerformed(evt);
            }
        });

        jLabel5.setText("#Desplazamiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(202, 202, 202))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jTextFieldDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1Encriptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2Limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3Desencriptar)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3Desencriptar)
                    .addComponent(jButton2Limpiar)
                    .addComponent(jButton1Encriptar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1EncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EncriptarActionPerformed
        // Obtener el valor de desplazamiento ingresado por el usuario
        int shift = obtenerDesplazamiento();
        if (shift == -1) {
            return; // Si el valor no es válido, salir del método
        }
        // Limpiar el área de texto cifrado antes de agregar nuevo contenido
        jTextArea2TextoCifrado.setText("");

        char[] arrCar = jTextArea1TextoPlano.getText().toUpperCase().toCharArray();
        for (int i = 0; i < arrCar.length; i++) {
            if (Character.isLetter(arrCar[i])) {
                // Aplicar cifrado César con el desplazamiento ingresado
                int num = ((arrCar[i] - 65 + shift) % 26) + 65;
                jTextArea2TextoCifrado.setText(jTextArea2TextoCifrado.getText() + (char) num);
            } else {
                // Conservar caracteres no alfabéticos
                jTextArea2TextoCifrado.setText(jTextArea2TextoCifrado.getText() + arrCar[i]);
            }
        }
    }//GEN-LAST:event_jButton1EncriptarActionPerformed

    private void jButton2LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LimpiarActionPerformed

        jTextArea1TextoPlano.setText("");
        //jTextArea1.setText(null);
    }//GEN-LAST:event_jButton2LimpiarActionPerformed

    private void jButton3DesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3DesencriptarActionPerformed
// Obtener el valor de desplazamiento ingresado por el usuario
        int shift = obtenerDesplazamiento();
        if (shift == -1) {
            return; // Si el valor no es válido, salir del método
        }
        String input = jTextArea2TextoCifrado.getText().toUpperCase();
        StringBuilder decrypted = new StringBuilder();

        for (char c : input.toCharArray()) {
            if (Character.isLetter(c)) {
                // Aplicar desencriptado César con el desplazamiento ingresado
                int num = ((c - 'A' - shift + 26) % 26) + 'A';
                decrypted.append((char) num);
            } else {
                // Conservar caracteres no alfabéticos
                decrypted.append(c);
            }
        }

        jTextArea1TextoPlano.setText(decrypted.toString());
    }//GEN-LAST:event_jButton3DesencriptarActionPerformed

    private void jTextFieldDesplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDesplazamientoActionPerformed
        // Validar el desplazamiento cuando se presiona Enter en el campo
        obtenerDesplazamiento();
    }//GEN-LAST:event_jTextFieldDesplazamientoActionPerformed

    /**
     * Método para obtener y validar el valor de desplazamiento
     *
     * @return el valor de desplazamiento entre 1 y 25, o -1 si es inválido
     */
    private int obtenerDesplazamiento() {
        try {
            int shift = Integer.parseInt(jTextFieldDesplazamiento.getText());
            if (shift < 1 || shift > 25) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El desplazamiento debe ser un número entre 1 y 25",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                jTextFieldDesplazamiento.setText("3");
                return -1;
            }
            return shift;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor ingrese un número válido entre 1 y 25",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            jTextFieldDesplazamiento.setText("3");
            return -1;
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMetodoCesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMetodoCesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMetodoCesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMetodoCesar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMetodoCesar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Encriptar;
    private javax.swing.JButton jButton2Limpiar;
    private javax.swing.JButton jButton3Desencriptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1TextoPlano;
    private javax.swing.JTextArea jTextArea2TextoCifrado;
    private javax.swing.JTextField jTextFieldDesplazamiento;
    // End of variables declaration//GEN-END:variables
}
