/*
 * Click nbproject://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbproject://SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author garci
 */
public class FrameScytale extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FrameScytale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1TextoPlano = new javax.swing.JTextArea();
        jButton1ENCRYPT = new javax.swing.JButton();
        jButton2Limpiar = new javax.swing.JButton();
        jButton3DECODE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2TextoEncriptado = new javax.swing.JTextArea();
        jTextField1Columnas = new javax.swing.JTextField();
        jTextField2Orden = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Metodo Scytale");

        jLabel2.setText("Texto Plano:");

        jTextArea1TextoPlano.setColumns(20);
        jTextArea1TextoPlano.setRows(5);
        jScrollPane1.setViewportView(jTextArea1TextoPlano);

        jButton1ENCRYPT.setText("ENCRYPT ");
        jButton1ENCRYPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ENCRYPTActionPerformed(evt);
            }
        });

        jButton2Limpiar.setText("Limpiar");
        jButton2Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LimpiarActionPerformed(evt);
            }
        });

        jButton3DECODE.setText("DECODE");
        jButton3DECODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DECODEActionPerformed(evt);
            }
        });

        jLabel3.setText("Texto Encriptado:");

        jTextArea2TextoEncriptado.setColumns(20);
        jTextArea2TextoEncriptado.setRows(5);
        jScrollPane2.setViewportView(jTextArea2TextoEncriptado);

        jTextField1Columnas.setText("4");
        jTextField1Columnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ColumnasActionPerformed(evt);
            }
        });

        jTextField2Orden.setText("3,1,4,2");

        jLabel4.setText("Orden");

        jLabel5.setText("Columnas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1Columnas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(224, 224, 224)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(0, 136, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton1ENCRYPT)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2Limpiar)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3DECODE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1Columnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2Orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1ENCRYPT)
                    .addComponent(jButton2Limpiar)
                    .addComponent(jButton3DECODE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ENCRYPTActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Encriptar texto usando el método Scytale
        String textoPlano = jTextArea1TextoPlano.getText();
        int numColumnas = Integer.parseInt(jTextField1Columnas.getText());
        int[] ordenColumnas = parsearOrdenColumnas(jTextField2Orden.getText(), numColumnas);
        
        String textoEncriptado = encriptarScytale(textoPlano, numColumnas, ordenColumnas);
        jTextArea2TextoEncriptado.setText(textoEncriptado);
    }                                               

    private void jButton2LimpiarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Limpiar ambos campos de texto
        jTextArea1TextoPlano.setText("");
        jTextArea2TextoEncriptado.setText("");
    }                                               

    private void jButton3DECODEActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Desencriptar texto usando el método Scytale
        String textoEncriptado = jTextArea2TextoEncriptado.getText();
        int numColumnas = Integer.parseInt(jTextField1Columnas.getText());
        int[] ordenColumnas = parsearOrdenColumnas(jTextField2Orden.getText(), numColumnas);
        
        String textoPlano = desencriptarScytale(textoEncriptado, numColumnas, ordenColumnas);
        jTextArea1TextoPlano.setText(textoPlano);
    }                                              

    private void jTextField1ColumnasActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // Acción cuando se presiona Enter en el campo de columnas
    }                                                   

    /**
     * Método para encriptar usando el método Scytale (transposición por columnas)
     */
    private String encriptarScytale(String texto, int numColumnas, int[] ordenColumnas) {
        // Eliminar todos los caracteres de espacio en blanco y convertir a mayúsculas
        String textoSinEspacios = texto.replaceAll("\\s+", "").toUpperCase();
        
        // Verificar si el texto está vacío
        if (textoSinEspacios.isEmpty()) {
            return "";
        }
        
        // Calcular número de filas necesarias
        int numFilas = (int) Math.ceil((double) textoSinEspacios.length() / numColumnas);
        int totalCaracteres = numFilas * numColumnas;
        
        // Crear matriz bidimensional
        char[][] matriz = new char[numFilas][numColumnas];
        
        // Llenar la matriz con el texto limpio por filas
        int index = 0;
        for (int fila = 0; fila < numFilas; fila++) {
            for (int col = 0; col < numColumnas; col++) {
                if (index < textoSinEspacios.length()) {
                    matriz[fila][col] = textoSinEspacios.charAt(index++);
                } else {
                    matriz[fila][col] = 'X'; // Rellenar con 'X' para completar
                }
            }
        }
        
        // Construir texto cifrado leyendo por columnas según el orden especificado
        StringBuilder cifrado = new StringBuilder();
        for (int colIndex : ordenColumnas) {
            int col = colIndex - 1; // Convertir a índice base 0
            for (int fila = 0; fila < numFilas; fila++) {
                cifrado.append(matriz[fila][col]);
            }
        }
        
        // Formatear el texto cifrado en bloques de 5 caracteres con espacios
        String textoCifrado = cifrado.toString();
        StringBuilder textoFormateado = new StringBuilder();
        for (int i = 0; i < textoCifrado.length(); i++) {
            textoFormateado.append(textoCifrado.charAt(i));
            if ((i + 1) % 5 == 0 && i + 1 < textoCifrado.length()) {
                textoFormateado.append(" ");
            }
        }
        
        return textoFormateado.toString();
    }
    
    /**
     * Método para desencriptar usando el método Scytale - CORREGIDO
     */
    private String desencriptarScytale(String textoCifrado, int numColumnas, int[] ordenColumnas) {
        // Eliminar espacios del texto cifrado para procesar correctamente
        textoCifrado = textoCifrado.replaceAll("\\s+", "");
        
        // Calcular número de filas
        int numFilas = textoCifrado.length() / numColumnas;
        
        // Crear matriz para reconstruir el texto original
        char[][] matriz = new char[numFilas][numColumnas];
        
        // Llenar la matriz con el texto cifrado según el orden de columnas
        int index = 0;
        for (int colIndex : ordenColumnas) {
            int col = colIndex - 1;
            for (int fila = 0; fila < numFilas; fila++) {
                if (index < textoCifrado.length()) {
                    matriz[fila][col] = textoCifrado.charAt(index++);
                }
            }
        }
        
        // Reconstruir el texto original leyendo por filas
        StringBuilder textoOriginal = new StringBuilder();
        for (int fila = 0; fila < numFilas; fila++) {
            for (int col = 0; col < numColumnas; col++) {
                textoOriginal.append(matriz[fila][col]);
            }
        }
        
        // Eliminar caracteres 'X' de relleno al final
        String textoSinRelleno = textoOriginal.toString().replaceAll("X+$", "");
        
        return textoSinRelleno;
    }
    
    /**
     * Método para parsear el orden de columnas ingresado por el usuario
     */
    private int[] parsearOrdenColumnas(String ordenStr, int numColumnas) {
        String[] partes = ordenStr.split(",");
        int[] orden = new int[numColumnas];
        boolean[] usado = new boolean[numColumnas + 1];
        int index = 0;
        
        for (String parte : partes) {
            if (index >= numColumnas) break;
            int col = Integer.parseInt(parte.trim());
            if (col >= 1 && col <= numColumnas && !usado[col]) {
                usado[col] = true;
                orden[index++] = col;
            }
        }
        
        // Rellenar con las columnas faltantes en orden
        for (int i = 1; i <= numColumnas; i++) {
            if (index >= numColumnas) break;
            if (!usado[i]) {
                orden[index++] = i;
            }
        }
        
        return orden;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameScytale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameScytale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameScytale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameScytale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameScytale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1ENCRYPT;
    private javax.swing.JButton jButton2Limpiar;
    private javax.swing.JButton jButton3DECODE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1TextoPlano;
    private javax.swing.JTextArea jTextArea2TextoEncriptado;
    private javax.swing.JTextField jTextField1Columnas;
    private javax.swing.JTextField jTextField2Orden;
    // End of variables declaration                   
}