/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rsa;
import java.security.*;
import java.security.spec.*;
import javax.crypto.Cipher;
import java.util.Base64;
import javax.swing.*;
import java.io.File;
import java.nio.file.Files;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
        
        
/**
 *
 * @author garci
 */
public class Ventana_RSA extends javax.swing.JFrame {
    java.security.KeyPair misLlaves;

    /**
     * Creates new form Ventana_RSA
     */
    public Ventana_RSA() {
        Security.removeProvider("BC"); 
Security.addProvider(new BouncyCastleProvider());
        initComponents();
        try {
            // Verifica si ya está cargado para no duplicar ni causar error
            if (java.security.Security.getProvider("BC") == null) {
                java.security.Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
            }
        } catch (Exception e) {
            System.out.println("Error cargando Bouncy Castle: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Seleccionar_Metodo = new javax.swing.JComboBox<>();
        btnGenerarClaves = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mi_llave_publica = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Mi_llave_privada = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Llave_amigo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Entrada = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnTestLocal = new javax.swing.JButton();
        btnEncriptar = new javax.swing.JButton();
        btnDesencriptar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane7.setViewportView(jTextArea6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Criptografía Asimétrica");

        Seleccionar_Metodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RSA", "Elgamal", "CurvasElipticas" }));

        btnGenerarClaves.setText("Generar llaves");
        btnGenerarClaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarClavesActionPerformed(evt);
            }
        });

        Mi_llave_publica.setColumns(20);
        Mi_llave_publica.setRows(5);
        jScrollPane1.setViewportView(Mi_llave_publica);

        jLabel1.setText("Llave Publica A");

        jLabel2.setText("Llave Privada A");

        jLabel3.setText("Llave Publica B");

        Mi_llave_privada.setColumns(20);
        Mi_llave_privada.setRows(5);
        jScrollPane2.setViewportView(Mi_llave_privada);

        Llave_amigo.setColumns(20);
        Llave_amigo.setRows(5);
        jScrollPane3.setViewportView(Llave_amigo);

        jLabel4.setText("Entrada");

        Entrada.setColumns(20);
        Entrada.setRows(5);
        jScrollPane4.setViewportView(Entrada);

        jLabel5.setText("Salida");

        Salida.setColumns(20);
        Salida.setRows(5);
        jScrollPane6.setViewportView(Salida);

        jLabel6.setText("jLabel6");

        btnTestLocal.setText("Test");
        btnTestLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestLocalActionPerformed(evt);
            }
        });

        btnEncriptar.setText("Encriptar");
        btnEncriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncriptarActionPerformed(evt);
            }
        });

        btnDesencriptar.setText("Desencriptar");
        btnDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesencriptarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Abrir Archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnEncriptar)
                                .addGap(26, 26, 26)
                                .addComponent(btnDesencriptar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                            .addComponent(jScrollPane6)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(Seleccionar_Metodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(btnGenerarClaves)
                                                .addGap(31, 31, 31)
                                                .addComponent(btnTestLocal)))))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Seleccionar_Metodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerarClaves)
                            .addComponent(btnTestLocal)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncriptar)
                    .addComponent(btnDesencriptar)
                    .addComponent(btnLimpiar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarClavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarClavesActionPerformed
        // TODO add your handling code here:
        try {
            String metodo = (String) Seleccionar_Metodo.getSelectedItem();
            KeyPairGenerator keyGen;
            
            // Configurar el generador según la selección
            switch (metodo) {
                case "RSA":
                    keyGen = KeyPairGenerator.getInstance("RSA");
                    keyGen.initialize(2048);
                    break;
                case "Elgamal":
                    // ElGamal requiere BouncyCastle (BC)
                    keyGen = KeyPairGenerator.getInstance("ElGamal", "BC");
                    keyGen.initialize(512); // O 1024
                    break;
                case "CurvasElipticas":
                    // ECC (EC) requiere BouncyCastle para facilitar ECIES
                    keyGen = KeyPairGenerator.getInstance("EC", "BC");
                    keyGen.initialize(256);
                    break;
                default:
                    return;
            }
            
            // Generar y guardar en variable global
            misLlaves = keyGen.generateKeyPair();
            
            // Mostrar en las cajas de texto (Codificado en Base64 para que sea legible)
            Mi_llave_publica.setText(Base64.getEncoder().encodeToString(misLlaves.getPublic().getEncoded()));
            Mi_llave_privada.setText(Base64.getEncoder().encodeToString(misLlaves.getPrivate().getEncoded()));
            
            JOptionPane.showMessageDialog(this, "Llaves generadas correctamente con " + metodo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar llaves: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarClavesActionPerformed

    private void btnEncriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncriptarActionPerformed
        // TODO add your handling code here:
        try {
            String mensaje = Entrada.getText();
            if (mensaje.isEmpty()) return;

            String metodo = (String) Seleccionar_Metodo.getSelectedItem();
            PublicKey llaveDestino;

            // 1. DECIDIR QUÉ LLAVE USAR
            if (Llave_amigo.getText().trim().isEmpty()) {
                // Si no hay llave de amigo, usamos la nuestra (Local Loopback)
                if (misLlaves == null) {
                    JOptionPane.showMessageDialog(this, "Primero genera tus llaves.");
                    return;
                }
                llaveDestino = misLlaves.getPublic();
            } else {
                // Si hay llave de amigo, la convertimos de Texto -> Objeto PublicKey
                byte[] keyBytes = Base64.getDecoder().decode(Llave_amigo.getText().trim());
                KeyFactory kf;
                
                if (metodo.equals("RSA")) {
                    kf = KeyFactory.getInstance("RSA");
                } else if (metodo.equals("Elgamal")) {
                    kf = KeyFactory.getInstance("ElGamal", "BC");
                } else { // Curvas Elipticas
                    kf = KeyFactory.getInstance("EC", "BC");
                }
                
                llaveDestino = kf.generatePublic(new X509EncodedKeySpec(keyBytes));
            }

            // 2. CONFIGURAR EL CIPHER (Algoritmo de encriptación)
            Cipher cipher;
            if (metodo.equals("RSA")) {
                cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
            } else if (metodo.equals("Elgamal")) {
                cipher = Cipher.getInstance("ElGamal/None/NoPadding", "BC");
            } else {
                cipher = Cipher.getInstance("ECIES", "BC");
            }

            // 3. ENCRIPTAR
            cipher.init(Cipher.ENCRYPT_MODE, llaveDestino);
            byte[] bytesEncriptados = cipher.doFinal(mensaje.getBytes());
            
            // Mostrar resultado en Base64
            Salida.setText(Base64.getEncoder().encodeToString(bytesEncriptados));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al encriptar: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEncriptarActionPerformed

    private void btnDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesencriptarActionPerformed
        // TODO add your handling code here:
        try {
            String mensajeCifradoStr = Entrada.getText(); // Ojo: Toma el texto cifrado de la Entrada
            if (mensajeCifradoStr.isEmpty() || misLlaves == null) {
                JOptionPane.showMessageDialog(this, "Necesitas un mensaje cifrado y tus llaves generadas.");
                return;
            }

            String metodo = (String) Seleccionar_Metodo.getSelectedItem();
            
            // 1. CONFIGURAR CIPHER
            Cipher cipher;
            if (metodo.equals("RSA")) {
                cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
            } else if (metodo.equals("Elgamal")) {
                cipher = Cipher.getInstance("ElGamal/None/NoPadding", "BC");
            } else {
                cipher = Cipher.getInstance("ECIES", "BC");
            }

            // 2. DESENCRIPTAR CON MI LLAVE PRIVADA
            cipher.init(Cipher.DECRYPT_MODE, misLlaves.getPrivate());
            
            byte[] bytesEncriptados = Base64.getDecoder().decode(mensajeCifradoStr);
            byte[] bytesDesencriptados = cipher.doFinal(bytesEncriptados);
            
            Salida.setText(new String(bytesDesencriptados));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al desencriptar (¿Llave incorrecta?): " + e.getMessage());
        }
    }//GEN-LAST:event_btnDesencriptarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        abrirArchivo();
    }                                          

    // Método auxiliar para no amontonar todo
    private void abrirArchivo() {
        JFileChooser fileChooser = new JFileChooser();
        int seleccion = fileChooser.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try {
                // Leer bytes y convertir a String
                String contenido = new String(Files.readAllBytes(archivo.toPath()));
                Entrada.setText(contenido);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error leyendo archivo: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnTestLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestLocalActionPerformed
        // TODO add your handling code here:
        try {
        // 1. VALIDACIONES PREVIAS
        if (misLlaves == null) {
            JOptionPane.showMessageDialog(this, "Error: Primero genera tus llaves (Botón Generar).");
            return;
        }
        String mensajeOriginal = Entrada.getText();
        if (mensajeOriginal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Escribe algo en el campo 'Entrada' para probar.");
            return;
        }

        String metodo = (String) Seleccionar_Metodo.getSelectedItem();
        
        // 2. CONFIGURAR EL CIPHER (El algoritmo matemático)
        Cipher cipher;
        if (metodo.equals("RSA")) {
            cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
        } else if (metodo.equals("Elgamal")) {
            cipher = Cipher.getInstance("ElGamal/None/NoPadding", "BC");
        } else { // Curvas Elípticas (ECIES)
            cipher = Cipher.getInstance("ECIES", "BC");
        }

        // --- PASO A: ENCRIPTAR (Con TU llave pública) ---
        cipher.init(Cipher.ENCRYPT_MODE, misLlaves.getPublic());
        byte[] bytesEncriptados = cipher.doFinal(mensajeOriginal.getBytes());
        String textoEncriptadoBase64 = Base64.getEncoder().encodeToString(bytesEncriptados);

        // --- PASO B: DESENCRIPTAR (Con TU llave privada) ---
        cipher.init(Cipher.DECRYPT_MODE, misLlaves.getPrivate());
        byte[] bytesDesencriptados = cipher.doFinal(bytesEncriptados);
        String mensajeRecuperado = new String(bytesDesencriptados);

        // 3. MOSTRAR EVIDENCIA (Salida visual para la tarea)
        Salida.setText("--- REPORTE DE PRUEBA LOCAL ---\n" +
                       "Método: " + metodo + "\n" +
                       "1. Mensaje Original: " + mensajeOriginal + "\n" +
                       "2. Encriptado (Base64): " + textoEncriptadoBase64 + "\n" +
                       "3. Desencriptado: " + mensajeRecuperado + "\n" +
                       "--------------------------------\n" +
                       "ESTADO: " + (mensajeOriginal.equals(mensajeRecuperado) ? "¡ÉXITO!" : "FALLÓ"));
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Falló la prueba local: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnTestLocalActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        // 1. Borrar contenido visual de las cajas de texto
    Entrada.setText("");
    Salida.setText("");
    Llave_amigo.setText("");
    Mi_llave_publica.setText("");
    Mi_llave_privada.setText("");
    
    // 2. IMPORTANTE: Reiniciar la variable global de llaves
    // Esto evita que intentes usar llaves viejas en un nuevo método
    misLlaves = null;
    
    // 3. (Opcional) Reiniciar el selector al primero (RSA)
    Seleccionar_Metodo.setSelectedIndex(0);
    
    // Feedback rápido (opcional, puedes quitarlo si te molesta)
    // JOptionPane.showMessageDialog(this, "Todo limpio. Listo para nueva prueba.");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_RSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_RSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Entrada;
    private javax.swing.JTextArea Llave_amigo;
    private javax.swing.JTextArea Mi_llave_privada;
    private javax.swing.JTextArea Mi_llave_publica;
    private javax.swing.JTextArea Salida;
    private javax.swing.JComboBox<String> Seleccionar_Metodo;
    private javax.swing.JButton btnDesencriptar;
    private javax.swing.JButton btnEncriptar;
    private javax.swing.JButton btnGenerarClaves;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTestLocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea6;
    // End of variables declaration//GEN-END:variables
}
